name: Build and Push Docker Images

on: 
  workflow_dispatch:
    inputs:
      webcerberusPackageFileName:
        description: The WebCerberus application prebuilded package file name
        required: true
        default: 'WebPersephoneApp_8.3.8648_kubernetes.tgz'
        type: choice
        options:
        - 'WebPersephoneApp_8.3.8648_kubernetes.tgz'
      pshPackageFileName:
        description: The PersephoneShell tool prebuilded package file name
        required: true
        default: 'PersephoneShell_2023.09.06_kubernetes.tgz'
        type: choice
        options:
        - 'PersephoneShell_2023.09.06_kubernetes.tgz'
      packageDownloadLinkURL:
        description: The URL of site where the packages are located
        required: true
        default: 'http://work.pandeiasoft.com/tmp/'
        type: choice
        options:
        - 'http://work.pandeiasoft.com/tmp/'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 'Get Persephone Shell package: ${{ inputs.webcerberusPackageFileName }}'
      run: mkdir ./Packages && curl ${{ inputs.packageDownloadLinkURL }}${{ inputs.webcerberusPackageFileName }} --output ./Packages/${{ inputs.webcerberusPackageFileName }}

    - name: Build and push WebCerberus image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfiles/Dockerfile_WebCerberus
        push: true
        tags: ykuharchuk/webcerberus:${{ github.ref }}
        build-args: |
          PackageFileName=${{ inputs.webcerberusPackageFileName }}

    - name: 'Get Persephone Shell package: ${{ inputs.webcerberusPackageFileName }}'
      run: curl ${{ inputs.packageDownloadLinkURL }}${{ inputs.pshPackageFileName }} --output ./Packages/${{ inputs.pshPackageFileName }}

    - name: Build and push PersephoneShell image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfiles/Dockerfile_PersephoneShell
        push: true
        tags: ykuharchuk/persephoneshell:${{ github.ref }}
        build-args: |
          PackageFileName=${{ inputs.pshPackageFileName }}

