name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push WebCerberus image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfiles/Dockerfile_WebCerberus
        push: true
        tags: persephonesoft/$(applicationImageName):${{ github.ref }}
        build-args: |
          PackageFileName=${{ parameters.PackageFileName }}

    - name: Build and push PersephoneShell image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfiles/Dockerfile_PersephoneShell
        push: true
        tags: persephonesoft/$(applicationImageName):${{ github.ref }}
        build-args: |
          PackageFileName=${{ parameters.PackageFileName }}
